name: push docker image

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Set image tag env
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ $BRANCH == 'master' || $BRANCH == 'main' ]];then
            TAG='latest'
          else
            TAG=$BRANCH
          fi
          echo "DockerTag=$TAG" >> $GITHUB_ENV
          echo "::notice::DockerTag=$TAG"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ env.DockerTag }}